theme: jekyll-theme-cayman
title: E-mage
site_url: https://emage.js.org
twitter: douglasjunior__

google_analytics: UA-125751709-1

show_downloads: true
github:
  download_url: https://github.com/douglasjunior/emage/releases
